import type { Metadata } from 'next'
import Link from 'next/link'
import {
  ComparePageShell,
  Breadcrumb,
  ComparisonTable,
  Disclosure,
} from '../components'

export const metadata: Metadata = {
  title: 'Terrarium vs JSX Viewer: Which React Previewer Is Right for You? (2026)',
  description:
    'Compare Terrarium and JSX Viewer side-by-side. Auto npm install vs pre-bundled libraries, live reload vs manual refresh, macOS-only vs cross-platform.',
  openGraph: {
    title: 'Terrarium vs JSX Viewer: Which React Previewer Is Right for You? (2026)',
    description:
      'Head-to-head comparison of two desktop apps for previewing AI-generated React components.',
    type: 'website',
  },
}

const featureRows = [
  { feature: 'Native desktop app', values: ['Yes (macOS)', 'Yes (macOS, Windows, Linux)'] },
  { feature: 'Zero configuration', values: ['Yes', 'Yes'] },
  { feature: 'Live reload on save', values: ['Yes', 'No'] },
  { feature: 'Drag-and-drop', values: ['Yes', 'Yes'] },
  { feature: 'Auto npm install', values: ['Yes (any package)', 'No (fixed set only)'] },
  { feature: 'Tailwind CSS built-in', values: ['Yes (v3, build-time)', 'Yes'] },
  { feature: 'shadcn/ui built-in', values: ['No', 'Yes'] },
  { feature: 'Recharts built-in', values: ['No', 'Yes'] },
  { feature: 'Lucide icons built-in', values: ['No', 'Yes'] },
  { feature: 'Claude Code integration', values: ['Yes (native)', 'No'] },
  { feature: 'Error overlay', values: ['Yes (with line numbers)', 'Yes'] },
  { feature: 'Multi-window', values: ['Yes', 'No'] },
  { feature: 'Dark mode', values: ['System default', 'Yes (system detection)'] },
  { feature: 'Zoom controls', values: ['No', 'Yes'] },
  { feature: 'Homebrew install', values: ['Yes', 'No'] },
  { feature: 'Cross-platform', values: ['No (macOS only)', 'Yes'] },
  { feature: 'License', values: ['MIT', 'MIT'] },
  { feature: 'Price', values: ['Free', 'Free'] },
]

export default function TerrariumVsJsxViewer() {
  return (
    <ComparePageShell>
      <Breadcrumb
        items={[
          { label: 'Home', href: '/' },
          { label: 'Compare', href: '/compare' },
          { label: 'Terrarium vs JSX Viewer' },
        ]}
      />

      <h1 className="font-serif text-4xl sm:text-5xl mb-4">
        Terrarium vs <span className="gradient-text">JSX Viewer</span>
      </h1>
      <p className="text-muted text-lg mb-12 max-w-2xl leading-relaxed">
        Two desktop apps built for the same job: instantly previewing React components
        generated by AI tools like Claude. Here&apos;s how they compare.
      </p>

      {/* TLDR */}
      <div className="glass rounded-2xl p-6 mb-12">
        <h2 className="font-semibold text-bright mb-3">TL;DR</h2>
        <p className="text-sm text-muted leading-relaxed">
          <strong className="text-bright">Terrarium</strong> auto-installs any npm package and
          live-reloads on save, making it ideal for iterative Claude Code workflows on macOS.{' '}
          <strong className="text-bright">JSX Viewer</strong> ships with pre-bundled shadcn/ui,
          Recharts, and Lucide icons and runs on all three desktop platforms — better if you need
          cross-platform support or those specific libraries out of the box.
        </p>
      </div>

      {/* Feature table */}
      <section className="mb-14">
        <h2 className="font-serif text-2xl mb-6">Feature comparison</h2>
        <ComparisonTable
          headers={['Feature', 'Terrarium', 'JSX Viewer']}
          rows={featureRows}
        />
      </section>

      {/* Where Terrarium wins */}
      <section className="mb-14">
        <h2 className="font-serif text-2xl mb-6">Where Terrarium wins</h2>
        <div className="space-y-6">
          <div className="glass rounded-xl p-5">
            <h3 className="font-semibold text-bright mb-2">Any npm package, automatically</h3>
            <p className="text-sm text-muted leading-relaxed">
              Terrarium scans your component for import statements and installs missing packages
              on the fly. If your Claude artifact uses <code className="text-accent">date-fns</code>,{' '}
              <code className="text-accent">framer-motion</code>, or any other npm package, Terrarium
              handles it. JSX Viewer only supports a fixed set of pre-bundled libraries — anything outside
              that set renders as a placeholder.
            </p>
          </div>
          <div className="glass rounded-xl p-5">
            <h3 className="font-semibold text-bright mb-2">Live reload on every save</h3>
            <p className="text-sm text-muted leading-relaxed">
              A file watcher re-bundles and re-renders your component every time you save.
              This is especially powerful paired with Claude Code — edits from Claude appear
              in the preview instantly without switching windows or clicking refresh.
              JSX Viewer requires you to manually re-open or refresh the file.
            </p>
          </div>
          <div className="glass rounded-xl p-5">
            <h3 className="font-semibold text-bright mb-2">Claude Code integration</h3>
            <p className="text-sm text-muted leading-relaxed">
              Run Terrarium in one terminal and Claude Code in another. Every save from
              Claude live-reloads the preview. This two-terminal workflow makes iterative
              component development feel seamless — describe a change, see it render.
            </p>
          </div>
          <div className="glass rounded-xl p-5">
            <h3 className="font-semibold text-bright mb-2">Multi-window support</h3>
            <p className="text-sm text-muted leading-relaxed">
              Open multiple TSX/JSX files simultaneously in separate windows. Compare variants
              side by side or keep a reference component visible while iterating on another.
            </p>
          </div>
        </div>
      </section>

      {/* Where JSX Viewer wins */}
      <section className="mb-14">
        <h2 className="font-serif text-2xl mb-6">Where JSX Viewer wins</h2>
        <div className="space-y-6">
          <div className="glass rounded-xl p-5">
            <h3 className="font-semibold text-bright mb-2">Cross-platform support</h3>
            <p className="text-sm text-muted leading-relaxed">
              JSX Viewer runs on macOS, Windows, and Linux with platform-specific installers
              (.dmg, .msi/.exe, .deb/.AppImage). Terrarium is macOS-only. If your team
              uses mixed operating systems, JSX Viewer is the more inclusive choice.
            </p>
          </div>
          <div className="glass rounded-xl p-5">
            <h3 className="font-semibold text-bright mb-2">Pre-bundled UI libraries</h3>
            <p className="text-sm text-muted leading-relaxed">
              JSX Viewer ships with shadcn/ui, Lucide React, Recharts, Radix UI, and
              class-variance-authority built in. If your Claude artifacts rely on these
              libraries (which many do), they render immediately with no install step.
            </p>
          </div>
          <div className="glass rounded-xl p-5">
            <h3 className="font-semibold text-bright mb-2">Zoom controls</h3>
            <p className="text-sm text-muted leading-relaxed">
              JSX Viewer includes zoom in/out controls for testing responsive designs at
              different scales. Useful for verifying how a component looks at various sizes
              without resizing the window.
            </p>
          </div>
          <div className="glass rounded-xl p-5">
            <h3 className="font-semibold text-bright mb-2">Graceful unknown-import handling</h3>
            <p className="text-sm text-muted leading-relaxed">
              When JSX Viewer encounters an import it doesn&apos;t recognize, it renders a visible
              placeholder instead of crashing. This makes it more forgiving when previewing
              components with uncommon dependencies.
            </p>
          </div>
        </div>
      </section>

      {/* Use case recommendations */}
      <section className="mb-14">
        <h2 className="font-serif text-2xl mb-6">Which should you choose?</h2>
        <div className="grid sm:grid-cols-2 gap-4">
          <div className="glass rounded-xl p-6 border-violet-500/20">
            <h3 className="font-semibold text-bright mb-3">Choose Terrarium if you&hellip;</h3>
            <ul className="text-sm text-muted space-y-2 leading-relaxed">
              <li className="flex gap-2"><span className="text-accent shrink-0">-</span> Use macOS as your primary development machine</li>
              <li className="flex gap-2"><span className="text-accent shrink-0">-</span> Work with Claude Code for iterative component development</li>
              <li className="flex gap-2"><span className="text-accent shrink-0">-</span> Need components that import arbitrary npm packages</li>
              <li className="flex gap-2"><span className="text-accent shrink-0">-</span> Want live reload without manual refreshing</li>
              <li className="flex gap-2"><span className="text-accent shrink-0">-</span> Prefer Homebrew for installation</li>
            </ul>
          </div>
          <div className="glass rounded-xl p-6 border-violet-500/20">
            <h3 className="font-semibold text-bright mb-3">Choose JSX Viewer if you&hellip;</h3>
            <ul className="text-sm text-muted space-y-2 leading-relaxed">
              <li className="flex gap-2"><span className="text-accent shrink-0">-</span> Need Windows or Linux support</li>
              <li className="flex gap-2"><span className="text-accent shrink-0">-</span> Primarily use shadcn/ui, Recharts, and Lucide in your artifacts</li>
              <li className="flex gap-2"><span className="text-accent shrink-0">-</span> Want responsive design testing with zoom controls</li>
              <li className="flex gap-2"><span className="text-accent shrink-0">-</span> Use multiple AI tools (ChatGPT, Claude, etc.) to generate components</li>
              <li className="flex gap-2"><span className="text-accent shrink-0">-</span> Prefer a self-contained app with no npm install step</li>
            </ul>
          </div>
        </div>
      </section>

      {/* Related comparisons */}
      <section className="mb-8">
        <h2 className="font-serif text-2xl mb-4">Related comparisons</h2>
        <div className="flex flex-col sm:flex-row gap-3">
          <Link href="/compare/terrarium-vs-claude-artifact-runner" className="glass glass-hover rounded-xl p-4 flex-1 block group">
            <span className="text-sm font-medium text-bright group-hover:text-accent transition-colors">
              Terrarium vs Claude Artifact Runner
            </span>
          </Link>
          <Link href="/compare/best-react-component-previewers-ai" className="glass glass-hover rounded-xl p-4 flex-1 block group">
            <span className="text-sm font-medium text-bright group-hover:text-accent transition-colors">
              5 Best React Component Previewers
            </span>
          </Link>
        </div>
      </section>

      <Disclosure />
    </ComparePageShell>
  )
}
